DELETE FROM daily_ideas 
WHERE date = CURRENT_DATE 
AND title IN (
  'TeleTherapy Match', 'NutriScan AI', 'SleepCoach Pro', 'VaxTrack Global', 
  'PharmaCost Compare', 'GutBiome Kit', 'ErgoDesk AI',
  'CropCast AI', 'StormShield Insurance', 'FloodSense IoT', 'SolarYield Forecast',
  'WindRoute Navigator', 'PollenGuard', 'EventWeather Pro', 'HeatMap Worker Safety',
  'FanPulse Analytics', 'InjuryPredict AI', 'YouthScout Network', 'GameDay Logistics',
  'TrainWithPros VR', 'RefAssist Vision', 'AthleteWallet', 'PickupGame Finder',
  'WasteNot Kitchen', 'FarmDirect Box', 'AllergyDine', 'GhostKitchen OS',
  'CulinaryAI Recipe', 'ProteinSwap Market', 'MenuTranslate AR', 'SchoolMeal Planner',
  'ScriptDoctor AI', 'IndieDistro Platform', 'SetSafe Monitor', 'CastingTape AI',
  'LocationScout VR', 'CrowdFund Cinema', 'SubSync Global', 'StreamRights Manager',
  'StemSplit Studio', 'GigRouter', 'RoyaltyLens', 'SampleClear Express',
  'FanClub DAO', 'PracticeRoom AR', 'VenueMatch Pro', 'MoodMix Curator',
  'MuseumPass Digital', 'HeritageMap AR', 'ArtistResidency Match', 'PublicArt Tracker',
  'FestivalOS', 'LanguageNest', 'CulturalExchange VR', 'IndigenousVoices Pod',
  'VirtualFit Room', 'CircularCloset', 'TextileTrace', 'TrendCast Engine',
  'CustomKnit Studio', 'SizeInclusive AI', 'FabricSwap B2B', 'StyleMentor AI',
  'OrbitDebris Tracker', 'LunarCargo Logistics', 'SatelliteSchool', 'AstroTourism Guide',
  'MicroGravity Lab', 'SpaceWeather Alert', 'CubeSat Builder Kit', 'EarthView Analytics',
  'PetHealth Tele', 'PawPrint DNA', 'BoardMatch Pet', 'PetInsure Flex',
  'AdoptMatch AI', 'PetFood Fresh', 'DogPark Finder', 'PetBehavior Coach',
  'VisaFast Track', 'EcoStay Certified', 'LocalGuide Connect', 'JetLag Cure',
  'PackSmart AI', 'NomadBase Hub', 'FlightDeal Sniper', 'AccessTravel Guide',
  'EVCharge Finder', 'AutoRepair AI', 'FleetElectrify', 'CarSubscribe Flex',
  'ParkSmart City', 'TireHealth Monitor', 'UsedCar Certify', 'RidePool Commuter',
  'BillTracker Citizen', 'FactCheck Instant', 'CampaignFinance Lens', 'CivicVoice Poll',
  'SanctionGuard B2B', 'PolicyImpact Sim', 'ElectionWatch AI', 'LobbyTrack Open',
  'LabEquip Share', 'PaperPeer Review', 'CitizenSci App', 'BioBank Connect',
  'GrantWriter AI', 'ClimateData Hub', 'SciComm Studio', 'QuantumLearn Platform',
  'BudgetBrain AI', 'TaxBot Freelance', 'MicroInvest Round', 'DebtFree Path',
  'CryptoTax Simple', 'RentSplit Fair', 'RetireReady Score', 'SideHustle Tracker',
  'TutorMatch AI', 'SkillBridge Bootcamp', 'ClassroomAI Assist', 'StudyGroup Sync',
  'CredentialStack', 'CampusSafe Alert', 'ParentPortal Plus', 'LabSim Virtual',
  'ReadingLevel AI', 'CollegeApp Coach',
  'CDC leadership vacuum deepens amid political turmoil',
  'FDA fast-track single-trial drug approvals',
  'Precipitation-adaptive event planning tool',
  'Inter-confederation match discovery platform',
  'EU breakfast reformulation advisor',
  'On-set injury response and production continuity AI',
  'Artist credit consent management platform',
  'Kennedy Center arts funding rescue network',
  'Celebrity-matched jewelry rental concierge',
  'SmallSat rideshare integration marketplace',
  'Exotic pet GPS and community recovery network',
  'Hawaii storm-disruption travel rebooking service',
  'Semi-solid battery retrofit marketplace for light trucks',
  'Geopolitical threat impact simulator for businesses',
  'Antimatter logistics safety certification',
  'Crude oil volatility shield for retail investors'
)